### PR TITLE
Kelly user actions

### PR DESCRIPTION
**Pull request by kellydobbs**
Changes Made:
- limited saving recipes to logged-in users
- limited reviewing recipes to logged-in users
- displays a message to non-logged-in users to log in or register
- dynamically grabs the User object of the logged-in user and relates the User object with the Review object when leaving a review
- displays username in the comments
- readded displaying the average rating and number of ratings
- refactored RecipeController and display.html to reduce redundant code

### CODE REVIEW

**Comment by paalwilliams** [comment]
Hey Kelly,

this looks great to me - I've been testing for about 10-15 minutes now and so far so good, no errors at all.

@Oksana999 @reynabiyo20 @missAH16 could one of you just do another review and confirm it looks good on your end :smile:

**Comment by Oksana999** [comment]
Kelly, the functionality you added in this pull request looks good. Great
job. Only the appearance of the stars is a little strange) Perhaps this is
only on my computer. Or can you make them better?

**Comment by kellydobbs** [comment]
Yeah, the stars are messed up in the master as well, but the functionality is still there. I know that Paal has a branch that he's working on for the CSS, so I figured I'd just leave it for now!

**Comment by reynabiyo20** [comment]
All good, Kelly. Great job as always. Thank you!

**Pull request merged**
