### PR TITLE
Add header-navigation

### PR DESCRIPTION
**Pull request by Oksana999**

### CODE REVIEW

**Comment by kellydobbs** [comment]
I just checked out master, and it looks like the "add to favorites" feature is no longer working.

**Comment by paalwilliams** [comment]
Thanks @kellydobbs for mentioning - admittedly i didn't test that part, so thats my bad. I'll take a look with @Oksana999  and figure it out!

**Comment by Oksana999** [comment]
Yes guys it was my favorite NullPointerExeption!

**Comment by Oksana999** [comment]
Yes guys it was my favorite NullPointerExeption.
I have fixed it. See my new PR
<https://github.com/LaunchCodeLiftoffProjects/recipesRus/pull/7>
Thank you all )

**Pull request merged**
